baseurl = "/"
languageCode = "en-us"
title = "Reality Punk"
theme = "hugo-theme-casper"
#disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "Misc misc misc"
  cover = "images/cover.jpg"
  author = "Sam Davies"
  authorlocation = "Melbourne, Australia"
  authorwebsite = "realitypunk.com"
  bio= "I am easting toast"
  logo = "images/logo.png"
  #googleAnalyticsUserID = "NA"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  #RSSLink = "http://feeds.feedburner.com/realitypunk.com"
  githubName = "Edible-Spam"
  twitterName = "Edible_Spam"
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
  [params.social]
    twitter = "Edible_Spam"